### ISSUE TITLE
Missing releases on GitHub

### ISSUE THREAD

**Issue by jayvdb** [kashifrazzaqui/again#8]
There have been releases on PyPI since 1.0, but no tags added at https://github.com/kashifrazzaqui/again/releases

To package this on openSUSE, I need to get access to the tests, which are not included in the PyPI sdists.
c.f. https://build.opensuse.org/package/show/home:jayvdb:py-new/python-again

**Comment by kashifrazzaqui** [comment]
Done, regret the inconvenience
